trigger: 
  branches:
    include:
      - master
      - feature/utc_cet_testing
parameters:
  - name: "envs"
    type: object
    default: ["DEV"]

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Install dependencies'
    workingDirectory: $(Build.SourcesDirectory)

  - script: |
      pytest test_python_task1.py
      displayName: 'Run pytest'
      workingDirectory: $(Build.SourcesDirectory)