trigger: 
  branches:
    include:
      - master

parameters:
  - name: "envs"
    type: object
    default: ["DEV"]
  - name: "factories"
    type: object
    default: ["MO46", "MO56", "MO93"]
  - name: run_blackduck
    type: boolean
    default: False

stages:
  - stage: release
    jobs:
      - job: FetchBuildId
        displayName: Fetch Build Id from Powershell script
        steps:
          - task: AzurePowerShell@2
            displayName: 'Run get build_id and work_items associated with the build_id'
            inputs:
              targetType: 'inline'
              scriptPath: |
                Write-Host "Running the powershell script .." 
                ./Automated_release_azure_devops/get_workitems_pbis_for_releases.ps1 

